/**
 * Env type is auto-generated by `wrangler types` in worker-configuration.d.ts.
 * It includes typed DurableObjectNamespace<T> generics, all bindings, and vars.
 * Re-exported here so existing `import { Env } from '../types'` continues to work.
 */
export type Env = Cloudflare.Env;

// Node Types as per spec
export type NodeType =
	| 'USER'
	| 'AGENT'
	| 'SESSION'
	| 'DOCUMENT'
	| 'FACT'
	| 'ENTITY'
	| 'INTENT'
	| 'TOPIC'
	| 'INSIGHT'
	| 'ACTION_ITEM'
	| 'PROFILE_SECTION'
	// Synced from database
	| 'NOTE'
	| 'TODO'
	| 'REMINDER'
	| 'FILE_REF';

// ============================================================================
// System Knowledge Namespace
// ============================================================================

/**
 * Special user ID for system-wide shared knowledge.
 * Used for ai_system_uploads that should be accessible to ALL users.
 * This creates a dedicated Graph DO and Vectorize namespace for system content.
 */
export const SYSTEM_KNOWLEDGE_USER_ID = '__SYSTEM_KNOWLEDGE__';

// Edge Types (Relationships)
export type EdgeType =
	| 'HAS_SESSION'
	| 'WITH_AGENT'
	| 'UPLOADED'
	| 'HAS_FACT'
	| 'HAS_INTENT'
	| 'HAS_PROFILE_SECTION'
	| 'MENTIONED'
	| 'REVEALS'
	| 'CONTAINS'
	| 'DISCUSSED'
	| 'DERIVED_FROM'
	| 'RELATES_TO'
	// Synced item relationships
	| 'HAS_NOTE'
	| 'HAS_TODO'
	| 'HAS_REMINDER'
	| 'HAS_FILE'
	| 'REFERENCED_IN'
	| 'EXTRACTED_FROM';

export interface GraphNode {
	id: string;
	type: NodeType;
	data: Record<string, any>;
	createdAt?: string;
	updatedAt?: string;
	decayScore?: number;
	confidence?: number;
}

export interface GraphEdge {
	source: string;
	target: string;
	relationship: EdgeType;
	properties?: Record<string, any>;
	createdAt?: string;
}

// Context returned for agent's Phase 1
export interface UserContext {
	userId: string;
	facts: GraphNode[];
	activeIntents: GraphNode[];
	recentSessions: GraphNode[];
	actionItems: GraphNode[];
	// Synced items
	notes: GraphNode[];
	todos: GraphNode[];
	reminders: GraphNode[];
	// File references
	chatFiles: GraphNode[]; // Files referenced in current chat
	accessibleFiles: GraphNode[]; // All files accessible to agent
}

// Extraction result from documents
export interface DocumentExtractionResult {
	docType: string;
	summary: string;
	entities: Array<{ name: string; type: string; properties?: Record<string, any> }>;
	facts: Array<{ text: string; category: string; confidence: number }>;
}

// Post-chat extraction result (session summarizer — facts/intents moved to ProfilerService)
export interface ConversationExtractionResult {
	summary: string;
	newEntities: Array<{
		name: string;
		type: string;
		expires_at?: string | null;
		supersedes?: string[];
	}>;
	mentionedTopics: string[];
}

// Search result for hybrid search
export interface SearchResult {
	id: string;
	text: string;
	context?: string;
	vectorScore?: number;
	ftsRank?: number;
	rrfScore?: number;
	rerankerScore?: number;
	normalizedScore?: number;
	source: 'vector' | 'fts' | 'hybrid';
	metadata?: Record<string, any>;
}

// Sync input types for DB → Graph sync
export interface NoteSyncInput {
	pbId: string; // Database record ID
	userId: string;
	title: string;
	content: string;
	tags?: string[];
	includeInMemory: boolean;
	shareWithAdmin: boolean;
	shareWithManager: boolean;
	createdAt: string;
	updatedAt: string;
}

export interface TodoSyncInput {
	pbId: string;
	userId: string;
	title: string;
	description?: string;
	status: 'pending' | 'in_progress' | 'completed' | 'cancelled';
	priority: 'low' | 'medium' | 'high' | 'urgent';
	dueDate?: string;
	includeInMemory: boolean;
	shareWithAdmin: boolean;
	shareWithManager: boolean;
	createdAt: string;
	updatedAt: string;
}

export interface ReminderSyncInput {
	pbId: string;
	userId: string;
	title: string;
	description?: string;
	reminderTime: string;
	recurring?: 'none' | 'daily' | 'weekly' | 'monthly';
	isActive: boolean;
	includeInMemory: boolean;
	shareWithAdmin: boolean;
	shareWithManager: boolean;
	createdAt: string;
	updatedAt: string;
}

export interface FileRefSyncInput {
	pbId: string; // user_uploads or ai_system_uploads ID
	userId: string;
	chatId?: string; // If referenced in a specific chat
	filename: string;
	fileType: string;
	vectorIds?: string[]; // Vectorize chunk IDs
	isPrivate: boolean;
	shareWithAgent: boolean;
	shareWithAdmin: boolean;
	shareWithManager: boolean;
	source: 'user' | 'system'; // user_uploads vs ai_system_uploads
	createdAt: string;
	updatedAt: string;
}

// Privacy filter for context queries
export interface PrivacyFilter {
	requestedBy: 'user' | 'agent' | 'admin' | 'manager';
	userId: string;
}
